# Test build daily
name: Daily build with tests

on:
    schedule:
      - cron:  '0 0 * * *'

jobs:
    build_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install java 11
              uses: actions/setup-java@v1
              with:
                java-version: "11"
            - name: Download ballerina distribution
              uses: wei/wget@v1
              with:
                args: https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.1.0/ballerina-2201.1.0-swan-lake.zip
            - run: mkdir extractedDistribution
            - name: Unzip ballerina distribution
              uses: TonyBogdanov/zip@1.0
              with:
                args: unzip -qq ./ballerina-2201.1.0-swan-lake.zip -d ./extractedDistribution
            - run: rm ballerina-2201.1.0-swan-lake.zip
            - run: npm ci
            - name: Build plugin with tests
              uses: GabrielBB/xvfb-action@v1.0
              with:
                run: ./gradlew clean build

    build_windows:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 12
        - name: Install java 11
          uses: actions/setup-java@v1
          with:
            java-version: "11"
        - run: mkdir extractedDistribution
        - name: Download Ballerina distribution
          run: Invoke-WebRequest -Uri https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.1.0/ballerina-2201.1.0-swan-lake.zip -OutFile extractedDistribution\ballerina-2201.1.0-swan-lake.zip
        - name: Unzip Ballerina distribution
          run: Expand-Archive -LiteralPath extractedDistribution\ballerina-2201.1.0-swan-lake.zip -DestinationPath extractedDistribution\
        - run: rm extractedDistribution\ballerina-2201.1.0-swan-lake.zip
        - run: npm ci -f
        - name: Build plugin with tests
          uses: GabrielBB/xvfb-action@v1.0
          with:
            run: ./gradlew clean build
